const assert=require("assert");
const {LLMClassifier}=require("../src/engine/llmClassifier");
const classifier=new LLMClassifier({provider:"deepseek"});
const config=classifier.getPublicConfig();
assert.equal(config.provider,"deepseek");
assert.equal(config.endpoint,"https://api.deepseek.com");
assert.equal(config.model,"deepseek-v4-flash");
assert.equal(config.apiKeyConfigured,false);
assert.equal(Object.prototype.hasOwnProperty.call(config,"apiKey"),false);
assert.deepEqual(classifier.validate(classifier.prepareUpdate({model:"deepseek-v4-flash",maxTokens:512})),[]);
assert.throws(()=>classifier.prepareUpdate({apiKey:"secret"}),/api_key_must_use_environment_variable/);
assert(classifier.validate(classifier.prepareUpdate({timeoutMs:100})).includes("timeout_invalid"));
assert.equal(classifier._parseResponse([{text:"{\"verdict\":\"block\",\"confidence\":0.9}"}]).verdict,"block");
const providers=classifier.getProviderCatalog();
assert(providers.length>=5);
const anthropic=classifier.prepareUpdate({provider:"anthropic"});
assert.equal(anthropic.endpoint,"https://api.anthropic.com");
assert.equal(anthropic.apiKeyEnv,"ANTHROPIC_API_KEY");
assert(anthropic.promptAnalysisTemplate.includes("AIDR"));
(async()=>{
  const result=await classifier.analyzePrompt("Read the README without changing files.");
  assert.equal(result.source,"rules_only");
  assert.equal(result.riskLevel,"unknown");
  const cached = new LLMClassifier({provider:"custom",enabled:true,model:"test-model"});
  let cachedCalls = 0;
  cached._callAndParse = async()=>{cachedCalls++;return {verdict:"allow",severity:"info",riskLevel:"low",riskScore:5,confidence:0.9,categories:[],capabilities:{}}};
  const first = await cached.analyzePrompt("same deterministic task");
  const second = await cached.analyzePrompt("same deterministic task");
  assert.equal(first.source,"semantic_model");
  assert.equal(second.source,"semantic_model");
  assert.equal(cachedCalls,1);
  assert.equal(cached.getStats().cacheHits,1);

  const failing = new LLMClassifier({provider:"custom",enabled:true,model:"test-model"});
  failing.circuitFailureThreshold=2;
  failing.circuitCooldownMs=10000;
  let failureCalls=0;
  failing._callAndParse = async()=>{failureCalls++;throw new Error("provider_unavailable")};
  const failOne = await failing.analyzePrompt("failure task one");
  const failTwo = await failing.analyzePrompt("failure task two");
  const failThree = await failing.analyzePrompt("failure task three");
  assert.equal(failOne.source,"rules_only");
  assert.equal(failTwo.source,"rules_only");
  assert.equal(failThree.explanation,"semantic_circuit_open");
  assert.equal(failureCalls,2);
  assert.equal(failing.getStats().circuitState,"open");
  assert.equal(failing.getStats().circuitRejected,1);
  console.log("llmClassifier tests passed");
})().catch(error=>{console.error(error);process.exit(1)});