const assert = require("assert");
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const { renderUi } = require("../endpoint");

const html = renderUi();
const match = html.match(/<script>([\s\S]*?)<\/script>/i);
assert(match, "UI script was not rendered");
new vm.Script(match[1], { filename: "aidr-endpoint-ui.js" });
assert(html.includes("AIDR Endpoint"));
assert(html.includes('id="page-overview"'));
assert(html.includes('id="page-sessions"'));
assert(html.includes('id="page-agents"'));
assert(html.includes('id="page-policy"'));
assert(html.includes('id="page-behavior"'));
assert(html.includes('id="page-semantic"'));
assert(html.includes('id="page-system"'));
assert(html.includes('id="aidr-runtime-adapter"'));
assert(html.includes('id="aidr-abgc-runtime"'), "Shared ABCG runtime must be embedded");
assert(html.includes('name="aidr-build-commit"'), "UI must expose the build commit");
assert(html.includes('name="aidr-ui-revision"'), "UI must expose the UI revision");
assert(html.includes("abg-behavior-orbit"));
assert(html.includes("abg-session-orbit"));
assert(html.includes("/api/behavior-atoms"));
assert(html.includes('var ABG_VIEW_TITLE = "Policy Orbit · 行为原子空间"'), "All ABCG views must share one title");
assert(html.includes("Codex"));
assert(html.includes('id="abgPolicySvg"'), "Policy Center must include the Policy Orbit canvas");
assert(html.includes('/api/diagnostics/data-quality?limit=1000'), "UI must load the canonical data-quality contract");
assert(require("fs").readFileSync(require("path").join(__dirname, "..", "endpoint.js"), "utf8").includes('"/api/diagnostics/data-quality"'), "Endpoint proxy must expose the data-quality contract");
assert(html.includes('id="abgBehaviorQuality"'), "Behavior monitoring must expose identity-link and freshness quality");
assert(html.includes('id="abgCapabilityGrid"'), "Policy Center must include the behavior atom lattice");
assert(html.includes('id="abgBehaviorSvg"'), "Behavior Monitoring must include the ABCG aggregate canvas");
assert(html.includes('id="abgSessionSvg"'), "Intent Analysis must include the session Policy Orbit");
assert(html.includes('api("/api/agents")'), "Agent Discovery must bind to the live Agent API");
assert(html.includes('api("/api/sessions?compact=1&limit=40")'), "Intent Analysis must bind to the live Session API");
assert(html.includes('api("/api/events?limit=100")'), "Behavior Monitoring must bind to the live Event API");
assert(html.includes('api("/api/behavior-atoms?windowHours=24&pathLimit=1000&occurrenceLimit=1000&sourceLimit=5000")'), "ABCG must request the complete behavior atom window");
assert(html.includes("abgBuildCompleteHitSpace(data, chosen)"), "Behavior Monitoring must render every hit atom from aggregate statistics");
assert(html.includes('data-behavior-metric="uniqueAtoms"'), "Behavior Monitoring must expose clickable atom statistics");
assert(html.includes('id="behaviorMetricModal"'), "Behavior Monitoring must provide metric detail dialogs");
assert(html.includes("behaviorMetricSnapshot()"), "Behavior Monitoring statistics must share the behavior-atom data source");
assert(!html.includes('id="abgBehaviorTimeline"'), "Behavior Orbit must not duplicate the real-time event list");
assert(!html.includes('id="abgBehaviorAgentName"'), "Behavior Orbit must not duplicate top-level behavior metrics");
assert(!html.includes("function ensureBehaviorOperations()"), "Behavior Monitoring must not recreate the duplicate disposition funnel");
assert(html.includes("selectBoundaryAtoms(catalog, boundary, layer, abgDomainKeys)"), "Policy boundaries must be anchored to effective behavior atoms");
assert(html.includes('if (mode === "disabled" && !outside) return false;'), "Policy-not-allowed filtering must use the effective organization boundary");
assert(html.includes("refreshBehaviorAtomPolicy().catch"), "Atom policy mutations must reconcile against a fresh boundary dataset");
assert(html.includes("policyRefresh="), "Atom policy refresh must bypass stale concurrent browser requests");
assert(html.includes("applyBehaviorAuthorizationSnapshot(result.authorization);"), "Policy Orbit must synchronously consume the mutation authorization snapshot");
assert(html.includes("abgPointInsidePolygon"), "Policy Orbit must detect denied atoms enclosed by the outer permission envelope");
assert(html.includes("abg-exclusion-boundary"), "Policy Orbit must render fixed-coordinate exclusion holes for denied atoms");
assert(!html.includes("projectedOutside: true"), "Behavior atom coordinates must never be moved to represent policy state");
assert(html.includes("abg-boundary-anchor organization"), "Organization boundary atom anchors must be rendered");
assert(fs.readFileSync(path.join(__dirname, "..", "endpoint.js"), "utf8").includes("agentGetCache.clear()"), "Mutations must invalidate Endpoint GET caches");
assert(html.includes('id="topContextTools"'), "Page tools must be merged into the canonical top bar");
assert(!html.includes('id="sessionPrompt"'), "Intent Analysis must not duplicate the selected session prompt");
assert(html.includes('data-evidence-tab="summary"'), "Session evidence must expose a summary tab");
assert(html.includes('data-evidence-tab="evidence"'), "Session evidence must expose an evidence tab");
assert(html.includes('data-evidence-tab="decision"'), "Session evidence must expose a decision tab");
assert(html.includes("data-disposition-trend"), "Overview must expose the live 24-hour disposition trend");
assert(html.includes("intent-reasoning-chain"), "Intent Analysis must render the explainable five-stage reasoning chain");
assert(html.includes("data-intent-atom"), "Intent Analysis atoms must link to Policy Orbit atoms");
assert(html.includes("analysisAssessment"), "Evidence confidence must use the structured analysis assessment");
assert(html.includes("initializePageToolbars()"), "Page headers must use the canonical top-bar toolbar registry");
assert(!html.includes('banner.id = "aidr-data-health"'), "The repeated global data-quality sentence must be removed");
assert(!html.includes('addEventListener("wheel"'), "Policy Orbit must not retain wheel zoom");
assert(!html.includes('addEventListener("pointermove"'), "Policy Orbit must not retain drag-to-pan");
assert(html.includes(".abg-orbit-box:fullscreen:before"), "Fullscreen Policy Orbit must expose the science-fiction grid treatment");
assert(html.includes('document.exitFullscreen?.()'), "Fullscreen Policy Orbit must provide a visible exit path");
assert.strictEqual((html.match(/id="aidr-runtime-adapter"/g) || []).length, 1, "Runtime adapter must be embedded exactly once");
assert.strictEqual((html.match(/id="aidr-abgc-runtime"/g) || []).length, 1, "ABCG runtime must be embedded exactly once");

console.log("endpoint UI template tests passed");
