const assert = require("assert");
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const { renderUi } = require("../endpoint");

const html = renderUi();
const match = html.match(/<script>([\s\S]*?)<\/script>/i);
assert(match, "UI script was not rendered");
new vm.Script(match[1], { filename: "aidr-endpoint-ui.js" });
assert(html.includes("AIDR Endpoint"));
assert(html.includes('id="page-overview"'));
assert(html.includes('id="page-sessions"'));
assert(html.includes('id="page-agents"'));
assert(html.includes('id="page-policy"'));
assert(html.includes('id="page-behavior"'));
assert(html.includes('id="page-semantic"'));
assert(html.includes('id="page-system"'));
assert(html.includes('id="aidr-runtime-adapter"'));
assert(html.includes('id="aidr-abgc-runtime"'), "Shared ABCG runtime must be embedded");
assert(html.includes('name="aidr-build-commit"'), "UI must expose the build commit");
assert(html.includes('name="aidr-ui-revision"'), "UI must expose the UI revision");
assert(html.includes("abg-behavior-orbit"));
assert(html.includes("abg-session-orbit"));
assert(html.includes("/api/behavior-atoms"));
assert(html.includes('var ABG_VIEW_TITLE = "Policy Orbit · 行为原子空间"'), "All ABCG views must share one title");
assert(html.includes("Codex"));
assert(html.includes('id="abgPolicySvg"'), "Policy Center must include the Policy Orbit canvas");
assert(html.includes('id="abgCapabilityGrid"'), "Policy Center must include the behavior atom lattice");
assert(html.includes('id="abgBehaviorSvg"'), "Behavior Monitoring must include the ABCG aggregate canvas");
assert(html.includes('id="abgSessionSvg"'), "Intent Analysis must include the session Policy Orbit");
assert(html.includes('api("/api/agents")'), "Agent Discovery must bind to the live Agent API");
assert(html.includes('api("/api/sessions?compact=1&limit=40")'), "Intent Analysis must bind to the live Session API");
assert(html.includes('api("/api/events?limit=100")'), "Behavior Monitoring must bind to the live Event API");
assert(html.includes('api("/api/behavior-atoms?windowHours=24&pathLimit=1000&occurrenceLimit=1000&sourceLimit=5000")'), "ABCG must request the complete behavior atom window");
assert(html.includes("abgBuildCompleteHitSpace(data, chosen)"), "Behavior Monitoring must render every hit atom from aggregate statistics");
assert(html.includes("selectBoundaryAtoms(catalog, boundary, layer, abgDomainKeys)"), "Policy boundaries must be anchored to effective behavior atoms");
assert(html.includes('if (mode === "disabled" && !outside) return false;'), "Policy-not-allowed filtering must use the effective organization boundary");
assert(html.includes("refreshBehaviorAtomPolicy().catch"), "Atom policy mutations must reconcile against a fresh boundary dataset");
assert(html.includes("policyRefresh="), "Atom policy refresh must bypass stale concurrent browser requests");
assert(html.includes("applyBehaviorAuthorizationSnapshot(result.authorization);"), "Policy Orbit must synchronously consume the mutation authorization snapshot");
assert(html.includes("abgPointInsidePolygon"), "Policy Orbit must detect denied atoms enclosed by the outer permission envelope");
assert(html.includes("abg-exclusion-boundary"), "Policy Orbit must render fixed-coordinate exclusion holes for denied atoms");
assert(!html.includes("projectedOutside: true"), "Behavior atom coordinates must never be moved to represent policy state");
assert(html.includes("abg-boundary-anchor organization"), "Organization boundary atom anchors must be rendered");
assert(fs.readFileSync(path.join(__dirname, "..", "endpoint.js"), "utf8").includes("agentGetCache.clear()"), "Mutations must invalidate Endpoint GET caches");
assert(html.includes('banner.id = "aidr-data-health"'), "UI must expose degraded data-source state");
assert.strictEqual((html.match(/id="aidr-runtime-adapter"/g) || []).length, 1, "Runtime adapter must be embedded exactly once");
assert.strictEqual((html.match(/id="aidr-abgc-runtime"/g) || []).length, 1, "ABCG runtime must be embedded exactly once");

console.log("endpoint UI template tests passed");
